# Generated by Django 4.0.4 on 2022-05-19 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('electronic', 'Electronic'), ('home and kitchen', 'Home and kitchen'), ('travel', 'Travel'), ('toy', 'Toy'), ('beauty', 'Beauty'), ('food', 'Food'), ('stationery', 'stationery')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pic', models.FileField(upload_to='product/')),
                ('description', models.TextField(max_length=200)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
