# Generated by Django 4.0.4 on 2022-05-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mycart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='product',
        ),
        migrations.AddField(
            model_name='mycart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mycart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
