# Generated by Django 4.0.4 on 2022-05-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_mycart_product_mycart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packing', 'Packing'), ('ready to dispatch', 'Ready to dispatch'), ('on the way', 'On the way'), ('oderd complate', 'Oderd complate')], default='pending', max_length=100)),
                ('payment_method', models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('online', 'Online')], max_length=50)),
                ('total_amount', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mycart')),
            ],
        ),
    ]
