# Generated by Django 4.0.4 on 2022-05-23 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_buyproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='oderd_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
