# Generated by Django 4.0.4 on 2022-05-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_buyproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='cart',
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.mycart'),
            preserve_default=False,
        ),
    ]
