# Generated by Django 4.0.4 on 2022-05-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_buyproduct_cart_buyproduct_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='cart',
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='cart',
            field=models.ManyToManyField(to='myapp.mycart'),
        ),
    ]
