# Generated by Django 4.0.4 on 2022-05-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_buyproduct_cart_buyproduct_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='product',
        ),
        migrations.AddField(
            model_name='mycart',
            name='product',
            field=models.ManyToManyField(to='myapp.product'),
        ),
    ]
