# Generated by Django 4.0.4 on 2022-05-24 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_mycart_product_mycart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproduct',
            name='cart',
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
