# Generated by Django 4.0.4 on 2022-05-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_buyproduct_cart_buyproduct_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproduct',
            old_name='oderd_date',
            new_name='ordered_date',
        ),
    ]
