# Generated by Django 4.0.4 on 2022-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_oderd_date_buyproduct_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packing', 'Packing'), ('ready to dispatch', 'Ready to dispatch'), ('on the way', 'On the way'), ('ordered complate', 'Ordered complate')], default='pending', max_length=100),
        ),
    ]
